### ISSUE TITLE
Adding Ring sensor + sync of the list

### ISSUE THREAD

**Issue by Strike2001** [athombv/io.nello#1]
The nello api should also expose the ring bell when someone push it , it would be very nice if this  door signal could show like a motion sensor symbol  or alarm symbol in homey devices and a flow for this 
when : 
door bell pushed / rings 

of this i still waited since i buy homey the combination with Trust 433 mhz bell in the garden / roof i could hear it on my complete home .

and if it is possible 
the list who opens the door could also be updated with the nello api and reverse . for example when a friend open with nello app or other api connection it is not added in the list of the homey device. in the orig nello app itself its complete they show when homey opens door. 

thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by WeeJeWel** [comment]
You can now create a Flow when the doorbell is rang.
