### ISSUE TITLE
Webhook Support not working

### ISSUE THREAD

**Issue by tobiaslins** [athombv/io.nello#2]
Hi @WeeJeWel .

I just installed the new Nello app and added my door to it.
Unlocking just works fine but if I ring, still no event is triggered!
An idea to debug this?

Should I see a webhook listed here?
https://developer.athom.com/webhooks

All the best and thanks for the app! :)

**Comment by WeeJeWel** [comment]
Hi Tobias,

If you've installed the Nello app through the app store, then the events should work. Try unlocking your door through the app and see if a Flow get started.

**Comment by tobiaslins** [comment]
Hi @WeeJeWel,
Thanks for your fast answer. I am also not receiving webhooks for this action. Do I need to manually set the webhook for Nello? 

Thanks!

**Comment by WeeJeWel** [comment]
No, should work automatically.

**Comment by WeeJeWel** [comment]
I just see the nello webhook hasn't fired for some time. I'll investigate.

**Comment by tobiaslins** [comment]
Should the webhook be listed in `https://developer.athom.com/webhooks`?

**Comment by WeeJeWel** [comment]
No

**Comment by WeeJeWel** [comment]
Fixed in Nello v1.1.1. Thank you for submitting the issue.
